spring:
  application:
    name: hw7
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_hw7
    username: artem
    password: 1385
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect